# Generated by Django 4.2.14 on 2024-08-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('late_evening', 'Late Evening')], max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='residents.resident')),
            ],
        ),
    ]
