# Generated by Django 4.1 on 2024-08-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0001_initial"),
        ("residents", "0002_medicationschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicationschedule",
            name="dosage",
        ),
        migrations.RemoveField(
            model_name="medicationschedule",
            name="medication",
        ),
        migrations.RemoveField(
            model_name="medicationschedule",
            name="time_of_day",
        ),
        migrations.CreateModel(
            name="MedicationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("late_evening", "Late Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dosage", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medications.medication",
                    ),
                ),
                (
                    "medication_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="residents.medicationschedule",
                    ),
                ),
            ],
        ),
    ]
